### ISSUE TITLE
civ 6 game crashes

### ISSUE THREAD

**Issue by tgaryo** [orkido/cheats#3]
I experience this when I click any of the buttons, I tried clicking set value and add value
![image](https://user-images.githubusercontent.com/80438485/110729408-94118680-8216-11eb-83a1-d71ee5cb655c.png)
![image](https://user-images.githubusercontent.com/80438485/110729441-a4296600-8216-11eb-94eb-91483e51db44.png)
Then on the next turn the game crashes with this error message
![image](https://user-images.githubusercontent.com/80438485/110729569-dc30a900-8216-11eb-9646-6ef08be308af.png)
How would I go about fixing this?

**Comment by orkido** [comment]
Thanks for reporting, bug is fixed. I forgot to remove a static offset that replaced the pattern matching offset scanner during testing.
Tested and working in singleplayer. If you use it in multiplayer, I would appreciate if you would report if it works or not.

**Comment by tgaryo** [comment]
It works in single i'll update when I play multiplayer, thanks alot!
